export interface ExpeditorModel {
    last_name: string,
    first_name: string,
    middle_name: string,
    phone: string,
    login: string,
    code: string,
    color: string,
    password: string,
    apk_version: string,
    application_access: boolean,
    territory_ids: any,
    warehouse_id: string,
    id: string,
    is_active: boolean,
}
