export const AppRoutes = {
    settings: "/settings",
    groupCategories: "/settings/customer-category",
    companyProfile: "/settings/company-profile",
    login: "/login",
    paymentMethods: "/currencies",
    units: "/units",
    territories: "/territories",
    clientCategories: "/client-categories",
    clientTypes: "/client-types",
    rejects: "/rejects",
    rejectDefects: "/reject-defects",
    photoReportCategories: "/photo-report-categories",
    inventoryTypes: "/inventory-types",
    users: "/users",
    orderComments: "/order-comments",
    taskTypes: "/task-types",
    boxTypes: "/box-types",
    knowledgeCategories: "/knowledge-categories",
};
